# fly.toml app configuration file generated for discord-python-starter-crimson-dream-4894 on 2025-06-05T12:02:54+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'discord-python-starter-crimson-dream-4894'
primary_region = 'lhr'

[build]

# Discord bots don't serve HTTP, they're background processes
[processes]
  app = "python -u src/bot.py"

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
  processes = ['app']

# Keep at least one machine running
[deploy]
  strategy = "immediate"
